apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: cart-pod-kill
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces: [default]
    labelSelectors:
      app: cartservice
  gracePeriod: 0
  duration: "5m"
