apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: volumetric-ddos-flood
  namespace: default
spec:
  mode: all
  selector:
    labelSelectors:
      app: frontend
  stressors:
    cpu:
      workers: 8
      load: 100
  duration: '3m'
