apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-redis
  namespace: default
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: redis-cart
  stressors:
    memory:
      workers: 2
      size: '200MB'
  duration: '2m'
